spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: system
    password: oracle
  liquibase:
    change-log: classpath:/db/changelog/001_create_file_import.sql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
import:
  directory: import/In
