version: '3.8'
services:
  oracle-db:
    image: gvenzl/oracle-xe
    environment:
      - ORACLE_PASSWORD=oracle
    ports:
      - 1521:1521
    volumes:
      - oracle-data:/opt/oracle/oradata
volumes:
  oracle-data:
